export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_PODCASTS_SUCCESS = 'LOAD_PODCASTS_SUCCESS';
export const LOAD_TOPICS_SUCCESS = 'LOAD_TOPICS_SUCCESS';
export const LOAD_SUBTOPICS_SUCCESS = 'LOAD_SUBTOPICS_SUCCESS'
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS'; 
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const WINDOW_SCROLL = 'WINDOW_SCROLL';