# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Create all default values for Topics table
Topic.create(topic: 'World')
Topic.create(topic: 'Politics')
Topic.create(topic: 'Business')
Topic.create(topic: 'Tech')
Topic.create(topic: 'Science')
Topic.create(topic: 'Sports')
Topic.create(topic: 'Arts')
Topic.create(topic: 'Race & Culture')
Topic.create(topic: 'Food')
Topic.create(topic: 'Travel')
Topic.create(topic: 'Education')
Topic.create(topic: 'Gaming')

# Create all default values for Subtopics table
world = Topic.where(topic: 'World')
politics = Topic.where(topic: 'Politics')
business = Topic.where(topic: 'Business')
tech = Topic.where(topic: 'Tech')
science = Topic.where(topic: 'Science')
sports = Topic.where(topic: 'Sports')
arts = Topic.where(topic: 'Arts')
race_and_culture = Topic.where(topic: 'Race & Culture')
food = Topic.where(topic: 'Food')
travel = Topic.where(topic: 'Travel')
education = Topic.where(topic: 'Education')
gaming = Topic.where(topic: 'Gaming')

Subtopic.create(subtopic: 'Crime', topic_id: politics.id)
Subtopic.create(subtopic: 'Drugs', topic_id: politics.id)
Subtopic.create(subtopic: 'Economy', topic_id: politics.id)
Subtopic.create(subtopic: 'Election', topic_id: politics.id)
Subtopic.create(subtopic: 'Energy', topic_id: politics.id)
Subtopic.create(subtopic: 'Environment', topic_id: politics.id)
Subtopic.create(subtopic: 'Fake News', topic_id: politics.id)
Subtopic.create(subtopic: 'Foreign Policy', topic_id: politics.id)
Subtopic.create(subtopic: 'Gun Control', topic_id: politics.id)
Subtopic.create(subtopic: 'Healthcare', topic_id: politics.id)
Subtopic.create(subtopic: 'Immigration', topic_id: politics.id)
Subtopic.create(subtopic: 'Taxes', topic_id: politics.id)
Subtopic.create(subtopic: 'Welfare', topic_id: politics.id)
Subtopic.create(subtopic: 'Economy', topic_id: business.id)
Subtopic.create(subtopic: 'Industry', topic_id: business.id)
Subtopic.create(subtopic: 'Markets', topic_id: business.id)
Subtopic.create(subtopic: 'Real Estate', topic_id: business.id)
Subtopic.create(subtopic: 'AI', topic_id: tech.id)
Subtopic.create(subtopic: 'Biotech', topic_id: tech.id)
Subtopic.create(subtopic: 'Blockchain', topic_id: tech.id)
Subtopic.create(subtopic: 'Cybersecurity', topic_id: tech.id)
Subtopic.create(subtopic: 'Design', topic_id: tech.id)
Subtopic.create(subtopic: 'Dev', topic_id: tech.id)
Subtopic.create(subtopic: 'Drones', topic_id: tech.id)
Subtopic.create(subtopic: 'Electric Cars', topic_id: tech.id)
Subtopic.create(subtopic: 'Gadgets', topic_id: tech.id)
Subtopic.create(subtopic: 'IoT', topic_id: tech.id)
Subtopic.create(subtopic: 'Robotics', topic_id: tech.id)
Subtopic.create(subtopic: 'Startups', topic_id: tech.id)
Subtopic.create(subtopic: 'VR/AR', topic_id: tech.id)
Subtopic.create(subtopic: 'Animals', topic_id: science.id)
Subtopic.create(subtopic: 'Energy', topic_id: science.id)
Subtopic.create(subtopic: 'Environment', topic_id: science.id)
Subtopic.create(subtopic: 'Health', topic_id: science.id)
Subtopic.create(subtopic: 'Space', topic_id: science.id)
Subtopic.create(subtopic: 'Baseball', topic_id: sports.id)
Subtopic.create(subtopic: 'Basketball', topic_id: sports.id)
Subtopic.create(subtopic: 'Cricket', topic_id: sports.id)
Subtopic.create(subtopic: 'Football', topic_id: sports.id)
Subtopic.create(subtopic: 'Hockey', topic_id: sports.id)
Subtopic.create(subtopic: 'NASCAR', topic_id: sports.id)
Subtopic.create(subtopic: 'Soccer', topic_id: sports.id)
Subtopic.create(subtopic: 'Tennis', topic_id: sports.id)
Subtopic.create(subtopic: 'UFC', topic_id: sports.id)
Subtopic.create(subtopic: 'Architecture', topic_id: arts.id)
Subtopic.create(subtopic: 'Comics', topic_id: arts.id)
Subtopic.create(subtopic: 'Fashion', topic_id: arts.id)
Subtopic.create(subtopic: 'Literature', topic_id: arts.id)
Subtopic.create(subtopic: 'Movies', topic_id: arts.id)
Subtopic.create(subtopic: 'Music', topic_id: arts.id)
Subtopic.create(subtopic: 'Performing', topic_id: arts.id)
Subtopic.create(subtopic: 'Photography', topic_id: arts.id)
Subtopic.create(subtopic: 'Television', topic_id: arts.id)
Subtopic.create(subtopic: 'Theatre', topic_id: arts.id)
Subtopic.create(subtopic: 'Visual', topic_id: arts.id)
Subtopic.create(subtopic: 'Class', topic_id: race_and_culture.id)
Subtopic.create(subtopic: 'Gender', topic_id: race_and_culture.id)
Subtopic.create(subtopic: 'Race', topic_id: race_and_culture.id)
Subtopic.create(subtopic: 'Religion', topic_id: race_and_culture.id)
Subtopic.create(subtopic: 'Sexuality', topic_id: race_and_culture.id)
Subtopic.create(subtopic: 'Africa', topic_id: world.id)
Subtopic.create(subtopic: 'Asia', topic_id: world.id)
Subtopic.create(subtopic: 'Australia', topic_id: world.id)
Subtopic.create(subtopic: 'Europe', topic_id: world.id)
Subtopic.create(subtopic: 'Middle East', topic_id: world.id)
Subtopic.create(subtopic: 'North America', topic_id: world.id)
Subtopic.create(subtopic: 'South America', topic_id: world.id)